/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import style from "../../styles/Home.module.css";
import Popup from "../components/Popup";
import { useState } from "react";

export default function Home() {
  const [Data, setData] = useState<any>([]);

  const [Buttonpop, setButtonPop] = useState<boolean>(false);

  const [Input, setInputData] = useState<any>({
    title: "",
    description: "",
    sdate: "",
    edate: "",
    status: "pending",
  });

  const [EditIndex, setEditIndex] = useState<any>(null)
  const [IsEdit, setIsEdit] = useState<boolean>(false);

  const submit = () => {
    

    if (IsEdit){
      let tempData = Data;
      tempData[EditIndex] = Input;
      setData(tempData);
      setEditIndex(null);
      setIsEdit(false);
      setInputData("")
      setButtonPop(false);
    }
    else if(Input) {
      setData([Input, ...Data]);
      setInputData("");
       setButtonPop(false);
    }
  };


  const handleDelete = (index: number) => {
    alert("Are You Sure??");

    const newList = Data.filter((item: any, i: number) => i != index);

    setData(newList);
  };

  const handleStatus = (index: number) => {
    if (Data[index].status == "pending") {
      alert("pending");
    } else {
      alert("completed");
    }
  };

  const handleEdit = (index: number) => {
    setInputData(Data[index]);
    setEditIndex(index);
    setIsEdit(true);
  };

  const handleMore = (index: number) => {};

  return (
    <div className={style.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <div className={style.main}>
       
        <div className={style.taskBox}>
          
          <div className={style.add}>
            <p>To - list project created by d-man</p>
            <button onClick={() => setButtonPop(true)}>Add Task</button>
            <Popup
              trigger={Buttonpop}
              setButtonPop={setButtonPop}
              setInputData={setInputData}
              Input={Input}
              submit={submit}
            />
          </div>

          <div className={style.taskList}>
            {Data.map((task: any, index: any) => {
              return (
                <div key={index} className={style.task}>
                  
                  <p>{task.title}</p>

                  <div className={style.taskbutton}>
                    <button onClick={() => handleMore(index)}>More</button>
                    <button onClick={() => handleDelete(index)}>Delete</button>
                    <button onClick={() => handleStatus(index)}>Status</button>
                    <button
                      onClick={() => {
                        handleEdit(index);
                        setButtonPop(true);
                      }}
                    >
                      Edit
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
